site_name: FloorPlan
site_description: 'Translate Room schemas to DBML'
site_author: 'Julio Zynger'
repo_name: 'julioz/FloorPlan'
repo_url: 'https://github.com/julioz/FloorPlan'

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - mdx_truly_sane_lists

theme:
  name: 'material'

nav:
  - 'Overview': 'index.md'
  - 'Usage':
      - 'Command-line': 'run.md'
      - 'Gradle Plugin': 'gradle-plugin.md'
      - 'Recipes':
        - 'Android Room': 'recipes/android-room.md'
        - 'SQLDelight': 'recipes/sqldelight.md'
  - 'Contributing': 'contributing.md'
  - 'Architecture': 'architecture.md'
  - 'Changelog': 'changelog.md'
